---
- name: Installing andrewrothstein.curl
  ansible.builtin.include_role:
    name: andrewrothstein.curl
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ porter_url }} to {{ porter_install_fq_target_sh }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ porter_url }}'
    dest: '{{ porter_install_fq_target_sh }}'
    mode: '755'
- name: Installing with {{ porter_install_fq_target_sh }}
  ansible.builtin.command: '{{ porter_install_fq_target_sh }}'
  changed_when: false
